name: Cursor Simple Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cursor-agent:
    runs-on: ubuntu-latest
    environment: CURSOR_API_KEY
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Install Cursor CLI
      run: |
        curl https://cursor.com/install -fsS | bash
        echo "$HOME/.cursor/bin" >> $GITHUB_PATH
    
    - name: Run Cursor Agent
      env:
        CURSOR_API_KEY: ${{ secrets.CURSOR_API_KEY }}
      run: |
        cursor-agent -p "Say I'm Cursor!" --model gpt-5 --output-format=text

    
